"""extending dummy table

Revision ID: 3fed57aeb43e
Revises: cd599cf6097f
Create Date: 2026-01-27 22:00:14.704438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fed57aeb43e'
down_revision: Union[str, Sequence[str], None] = 'cd599cf6097f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('new_description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('new_category', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('new_is_active', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('new_priority_level', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('new_budget', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('new_start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('new_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'new_end_date')
    op.drop_column('projects', 'new_start_date')
    op.drop_column('projects', 'new_budget')
    op.drop_column('projects', 'new_priority_level')
    op.drop_column('projects', 'new_is_active')
    op.drop_column('projects', 'new_category')
    op.drop_column('projects', 'new_description')
    op.drop_column('projects', 'new_name')
    # ### end Alembic commands ###
