nav:
- Home: index.md
- Requirements: requirements.md
- Installation: installation.md
- Usage: usage.md
- About:
  - License: license.md
  - Release Notes: https://github.com/project-sthali/sthali-auth/releases
  - Issue Tracker: https://github.com/project-sthali/sthali-auth/issues
- API Reference:
  - AppSpecification: api/class_AppSpecification.md
  - Config: api/class_Config.md
  - Sthaliauth: api/class_Sthaliauth.md
  - default_lifespan: api/function_default_lifespan.md
repo_name: sthali-auth
repo_url: https://github.com/project-sthali/sthali-auth/
site_author: Jhunu Fernandes
site_description: A FastAPI package dependency for keep Sthali safe
site_name: sthali-auth
site_url: https://project-sthali.github.io/sthali-auth/
theme: readthedocs
